version: '3.9'

services:
  backend:
    container_name: backend
    restart: always
    command: python3 __main__.py
    env_file: .env
    build:
      context: ./app
      dockerfile: app.dockerfile
    depends_on:
      - db
    networks:
      - app-network

  db:
    container_name: db
    image: postgres:16
    env_file: db.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  caddy:
    image: caddy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data  # Для хранения сертификатов Let's Encrypt
    networks:
      - app-network
    depends_on:
      - frontend
      # - backend

#   frontend:
#     container_name: ez-frontend
#     restart: unless-stopped
#     env_file: front/.env
#     build:
#       context: ./front
#       dockerfile: front.dockerfile
#     depends_on:
#       - backend
#     expose:
#       - 3000
volumes:
  postgres-data:
  caddy_data:
#   caddy_config:

networks:
  app-network:
    driver: bridge
